[package]
name = "backend_bin"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
backend_lib = { path = "../lib" }
tokio = { version = "1.45.1", features = ["full"] }

